### ISSUE TITLE
Error while try to enter more than 10 characters in licensePlateTextField

### ISSUE THREAD

**Issue by KienVu1504** [KienVu1504/Parking-Management-System#3]
- Show error on console after select bicycles check box then select another vehicle type, go to license plate text field and try to fill more than 10 characters.

Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: The start must be <= the end
	at javafx.controls/javafx.scene.control.TextInputControl.getText(TextInputControl.java:459)
	at javafx.controls/javafx.scene.control.TextInputControl.updateContent(TextInputControl.java:573)
	at javafx.controls/javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:564)
	at javafx.controls/javafx.scene.control.skin.TextFieldSkin.replaceText(TextFieldSkin.java:450)
	at javafx.controls/com.sun.javafx.scene.control.behavior.TextFieldBehavior.replaceText(TextFieldBehavior.java:179)
	at javafx.controls/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.defaultKeyTyped(TextInputControlBehavior.java:402)
	at javafx.controls/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(TextInputControlBehavior.java:332)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4105)
	at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2156)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2630)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249)
	at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:548)
	at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:972)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by KienVu1504** [comment]
Limited capacity of **`randomLP()`** from 10 to 9.
```
StringBuilder sb = new StringBuilder(9);
for (int i = 0; i < 9; i++) {
  // generate a random number between
  // 0 to AlphaNumericString variable length
  int index
    = (int) (AlphaNumericString.length()
    * Math.random());
  // add Character one by one in end of sb
  sb.append(AlphaNumericString
    .charAt(index));
}
```
